apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: permitteringsmelding-notifikasjon-alert
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  receivers:
    slack:
      channel: permittering-og-nedbemanning-alerts
      prependText: '<!here> | '
  alerts:
    - alert: Applikasjon nede
      expr: sum(up{app="permitteringsmelding-notifikasjon", job="kubernetes-pods"}) == 0
      for: 2m
      description: "App {{ $labels.log_app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    - alert: Det har skjedd en feil i permitteringsmelding-notifikasjon, logget med level Error
      expr: sum(increase(logd_messages_total{log_app="permitteringsmelding-notifikasjon",log_level="Error"}[10m])) > 0
      for: 10s
      description: "permitteringsmelding-notifikasjon har logget en feil"
      action: "Sjekk logs.adeo.no for logger"